remove num_class = 1
line caused this error: 
"Failure reason
ClientError: Do not need to setup parameter 'num_class' for learning task other than multi classification."

Removing it allowed the job to finish.